### ISSUE TITLE
Support user config via environment variables / docker-compose.yml

### ISSUE THREAD

**Issue by clach04** [timo-reymann/chrooted-ftp#34]
### Description

As an optional alternative to users file, allow defining users via environment variables. For an example see https://github.com/ServerContainers/samba/blob/master/docker-compose.yml

    environment:
      ACCOUNT_alice: alipass
      ACCOUNT_bob: bobpass

Could also implement home directory config in a similar manner, https://github.com/timo-reymann/chrooted-ftp/issues/30.

**Comment by timo-reymann** [comment]
I like the idea, especially since it feels more natural to use env vars in container context.

As complexity grows a bit I am really thinking it would make sense to rewrite the entrypoint to golang, to provide greater flexibility. It would also be a nice oppurtunity to drop the shells and command line utils for the startup, basically allowing to strip down the image even more.

Will take a look at this and come up with a solution for this and plan for the future.

**Comment by timo-reymann** [comment]
> As complexity grows a bit I am really thinking it would make sense to rewrite the entrypoint to golang, to provide greater flexibility. It would also be a nice oppurtunity to drop the shells and command line utils for the startup, basically allowing to strip down the image even more.

Check it and the effort would not be worth it, also image would be bigger.

Will implement in plain shell

**Comment by timo-reymann** [comment]
:heavy_check_mark: Shipped with 3.2.0
